***Import the attached Netflix csv file in Jupyter notebook and perform following operations using Pandas***

In [1]:
import numpy as np
import pandas as pd

In [9]:
# Optimize output window

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [3]:
df=pd.read_csv('Netflix.csv')

In [11]:
#Print the first 5 rows and last 5 rows of the dataframe
print(f"The first five rows of the dataset \n {df.head()}")

The first five rows of the dataset
   show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                                                                                                                                                                                                                                                                              cast  \
0                                                                                                                                                                                                                                                                                                              NaN
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng
2                                                                                                                                                              Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera
3                                                                                                                                                                                                                                                                                                              NaN
4                                                                                                                                                                                                         Mayur More, Jitendra Kumar, Ranjan Raj, Alam Khan, Ahsaas Channa, Revathi Pillai, Urvi Singh, Arun Kumar

         country          date_added  release_year rating   duration  \
0  United States  September 25, 2021          2020  PG-13     90 min
1   South Africa  September 24, 2021          2021  TV-MA  2 Seasons
2            NaN  September 24, 2021          2021  TV-MA   1 Season
3            NaN  September 24, 2021          2021  TV-MA   1 Season
4          India  September 24, 2021          2021  TV-MA  2 Seasons

                                                       listed_in
0                                                  Documentaries
1                International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Action & Adventure
3                                         Docuseries, Reality TV
4         International TV Shows, Romantic TV Shows, TV Comedies

In [12]:
print(f"The last five rows of the dataset \n {df.tail()}")

The last five rows of the dataset
      show_id     type        title         director  \
8775   s8803    Movie       Zodiac    David Fincher
8776   s8804  TV Show  Zombie Dumb              NaN
8777   s8805    Movie   Zombieland  Ruben Fleischer
8778   s8806    Movie         Zoom     Peter Hewitt
8779   s8807    Movie       Zubaan      Mozez Singh

                                                                                                                                                             cast  \
8775  Mark Ruffalo, Jake Gyllenhaal, Robert Downey Jr., Anthony Edwards, Brian Cox, Elias Koteas, Donal Logue, John Carroll Lynch, Dermot Mulroney, Chloë Sevigny
8776                                                                                                                                                          NaN
8777                                                          Jesse Eisenberg, Woody Harrelson, Emma Stone, Abigail Breslin, Amber Heard, Bill Murray, Derek Graf
8778                                      Tim Allen, Courteney Cox, Chevy Chase, Kate Mara, Ryan Newman, Michael Cassidy, Spencer Breslin, Rip Torn, Kevin Zegers
8779                        Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanana, Manish Chaudhary, Meghna Malik, Malkeet Rauni, Anita Shabdish, Chittaranjan Tripathy

            country         date_added  release_year rating   duration  \
8775  United States  November 20, 2019          2007      R    158 min
8776            NaN       July 1, 2019          2018  TV-Y7  2 Seasons
8777  United States   November 1, 2019          2009      R     88 min
8778  United States   January 11, 2020          2006     PG     88 min
8779          India      March 2, 2019          2015  TV-14    111 min

                                           listed_in
8775                  Cult Movies, Dramas, Thrillers
8776          Kids' TV, Korean TV Shows, TV Comedies
8777                         Comedies, Horror Movies
8778              Children & Family Movies, Comedies
8779  Dramas, International Movies, Music & Musicals

In [ ]:
# Check how many rows and columns are there using Pandas function.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8780 entries, 0 to 8779
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8780 non-null   str
 1   type          8780 non-null   str
 2   title         8780 non-null   str
 3   director      6150 non-null   str
 4   cast          7956 non-null   str
 5   country       7952 non-null   str
 6   date_added    8770 non-null   str
 7   release_year  8780 non-null   int64
 8   rating        8776 non-null   str
 9   duration      8780 non-null   str
 10  listed_in     8780 non-null   str
dtypes: int64(1), str(10)
memory usage: 754.7 KB

In [14]:
# Print all the column names.

df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='str')

In [ ]:
#	Calculate the descriptive statistics of all the variables(integer/float/object etc).
df.describe(include='all')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
count,8780,8780,8780,6150,7956,7952,8770,8780.000000,8776,8780,8780
unique,8780,2,8780,4516,7671,745,1765,NaN,14,220,514
top,s1,Movie,Dick Johnson Is Dead,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",NaN,TV-MA,1 Season,"Dramas, International Movies"
freq,1,6110,1,19,19,2809,108,NaN,3198,1788,361
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.178474,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.827938,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1925.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN

In [18]:
#Check the number of unique values for each column.

df.nunique()

show_id         8780
type               2
title           8780
director        4516
cast            7671
country          745
date_added      1765
release_year      74
rating            14
duration         220
listed_in        514
dtype: int64

In [21]:
# Check the percentage of missing values for each column.

(df.isnull().sum())/(len(df))*100

show_id          0.000000
type             0.000000
title            0.000000
director        29.954442
cast             9.384966
country          9.430524
date_added       0.113895
release_year     0.000000
rating           0.045558
duration         0.000000
listed_in        0.000000
dtype: float64

In [ ]:
#Delete all the rows where Director column has missing values.
df.dropna(subset=['director'])

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Action & Adventure"
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, Henry Thomas, Kristin Lehman, Samantha Sloyan, Igby Rigney, Rahul Kohli, Annarah Cymone, Annabeth Gish, Alex Essoe, Rahul Abburi, Matt Biedel, Michael Trucco, Crystal Balint, Louis Oliver",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, Sofia Carson, Liza Koshy, Ken Jeong, Elizabeth Perkins, Jane Krakowski, Michael McKean, Phil LaMarr",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri","United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...,...
8774,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, Mansoor Alfeeli, Ahd","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers"
8775,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey Jr., Anthony Edwards, Brian Cox, Elias Koteas, Donal Logue, John Carroll Lynch, Dermot Mulroney, Chloë Sevigny",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers"
8777,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, Abigail Breslin, Amber Heard, Bill Murray, Derek Graf",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies"
8778,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Mara, Ryan Newman, Michael Cassidy, Spencer Breslin, Rip Torn, Kevin Zegers",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies"
8779,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanana, Manish Chaudhary, Meghna Malik, Malkeet Rauni, Anita Shabdish, Chittaranjan Tripathy",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals"

In [ ]:
#Print all the records where country has Germany value (including West Germany). If any other country is there along with Germany, then that row should also come in output.
df[df['country'].str.contains('Germany', case=False, na=False)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,Germany,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng",Germany,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera",Germany,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Action & Adventure"
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,Germany,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV"
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam Khan, Ahsaas Channa, Revathi Pillai, Urvi Singh, Arun Kumar",Germany,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV Comedies"
...,...,...,...,...,...,...,...,...,...,...,...
8775,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey Jr., Anthony Edwards, Brian Cox, Elias Koteas, Donal Logue, John Carroll Lynch, Dermot Mulroney, Chloë Sevigny",Germany,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers"
8776,s8804,TV Show,Zombie Dumb,NaN,NaN,Germany,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies"
8777,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, Abigail Breslin, Amber Heard, Bill Murray, Derek Graf",Germany,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies"
8778,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Mara, Ryan Newman, Michael Cassidy, Spencer Breslin, Rip Torn, Kevin Zegers",Germany,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies"
8779,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanana, Manish Chaudhary, Meghna Malik, Malkeet Rauni, Anita Shabdish, Chittaranjan Tripathy",Germany,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals"

In [ ]:
#Expand Duration column into 2 separate columns – First column having the numeric value and other having String. Eg: 3 seasons should be split in 2 columns having 3 in 1st column and seasons in 2nd column.
df[['Duration_Value', 'Duration_Type']] = (df['duration'].str.extract(r'(\d+)\s+(.*)'))

In [38]:
df['Duration_Value']=df['Duration_Value'].astype(int)

In [39]:
df['Duration_Value'].dtypes

dtype('int64')

In [40]:
# Split Date added into 3 separate columns having date value in 1st column, month value in 2nd column and year value in 3rd.
df[['Month', 'Day', 'Year']] = df['date_added'].str.extract( r'([A-Za-z]+)\s+(\d+),\s+(\d+)')

In [ ]:
# Print the number of TV shows/Movies released in each year.
df.groupby('release_year')['show_id'].count()

release_year
1925       1
1942       2
1943       3
1944       3
1945       4
        ...
2017    1030
2018    1141
2019    1024
2020     952
2021     592
Name: show_id, Length: 74, dtype: int64

In [43]:
#Rename the column title with movie_title
df.rename(columns={'tile':'movie_title'},inplace=True)

In [44]:
#Split Listed_in column into 3 different columns with col name (Genre1, Genre2, Genre3). Split the column based on comma.
df[['Genre1', 'Genre2', 'Genre3']] = df['listed_in'].str.split(',', n=2, expand=True)

***Import both the attached files (student.csv and marks.csv) in Jupyter notebook and perform following operations:***

In [99]:
# import the files
student_df=pd.read_csv('student.csv')
marks_df=pd.read_csv('marks.csv')

In [100]:
#Combine both the dataframes into single dataframe which will have all the records from both the tables.
print(f"The Student dataset \n {student_df.head()}")
print(f"The Marks dataset \n {marks_df.head()}")

The Student dataset
    Student_id  Age  Gender      Grade Employed
0           1   19    Male  1st Class      yes
1           2   20  Female  2nd Class       no
2           3   18    Male  1st Class       no
3           4   21  Female  2nd Class       no
4           5   19    Male  1st Class       no
The Marks dataset
    Student_id  Mark     City
0           1    95  Chennai
1           2    70    Delhi
2           3    98   Mumbai
3           4    75     Pune
4           5    89    Kochi

In [101]:
#checking for null values
student_df.isnull().sum()

Student_id    0
Age           0
Gender        0
Grade         0
Employed      0
dtype: int64

In [102]:
marks_df.isnull().sum()

Student_id    0
Mark          0
City          0
dtype: int64

In [103]:
# Join two tables
combined_df=pd.merge(student_df,marks_df,on='Student_id',how='outer')
combined_df

     Student_id  Age  Gender      Grade Employed  Mark     City
0             1   19    Male  1st Class      yes  95.0  Chennai
1             2   20  Female  2nd Class       no  70.0    Delhi
2             3   18    Male  1st Class       no  98.0   Mumbai
3             4   21  Female  2nd Class       no  75.0     Pune
4             5   19    Male  1st Class       no  89.0    Kochi
..          ...  ...     ...        ...      ...   ...      ...
227         228   21  Female  1st Class       no  99.0     Pune
228         229   20    Male  2nd Class       no  70.0  Chennai
229         230   20    Male  3rd Class      yes  55.0    Delhi
230         231   19  Female  1st Class      yes  97.0   Mumbai
231         232   20    Male  3rd Class      yes  59.0     Pune

[232 rows x 7 columns]

In [104]:
#Print the maximum and minimum marks Gender wise.

combined_df.groupby('Gender')['Mark'].agg(['min','max'])

         min    max
Gender
Female  40.0   99.0
Male    40.0  100.0

In [105]:
#Print all the students IDs and their marks who have scored more than the average marks of the class.
combined_df[combined_df['Mark']> (combined_df['Mark'].sum())/len(combined_df)]

     Student_id  Age  Gender      Grade Employed  Mark     City
0             1   19    Male  1st Class      yes  95.0  Chennai
2             3   18    Male  1st Class       no  98.0   Mumbai
3             4   21  Female  2nd Class       no  75.0     Pune
4             5   19    Male  1st Class       no  89.0    Kochi
11           12   20    Male  1st Class       no  90.0    Kochi
..          ...  ...     ...        ...      ...   ...      ...
222         223   19    Male  2nd Class       no  79.0  Gwalior
224         225   19    Male  2nd Class       no  72.0  Chennai
225         226   21  Female  2nd Class      yes  71.0    Delhi
227         228   21  Female  1st Class       no  99.0     Pune
230         231   19  Female  1st Class      yes  97.0   Mumbai

[139 rows x 7 columns]

In [106]:
#Print the dataframe who are Males and are Employed.
combined_df[(combined_df['Gender']=="Male") & (combined_df['Employed']=="yes")]

     Student_id  Age Gender      Grade Employed  Mark     City
0             1   19   Male  1st Class      yes  95.0  Chennai
5             6   20   Male  2nd Class      yes  69.0  Gwalior
7             8   21   Male  3rd Class      yes  54.0  Chennai
12           13   19   Male  1st Class      yes  92.0  Gwalior
14           15   19   Male  1st Class      yes  97.0     Pune
16           17   20   Male  2nd Class      yes  68.0  Gwalior
18           19   21   Male  2nd Class      yes  72.0  Chennai
29           30   19   Male  1st Class      yes  81.0  Chennai
34           35   20   Male  2nd Class      yes  79.0  Gwalior
36           37   21   Male  3rd Class      yes  53.0     Pune
41           42   19   Male  1st Class      yes  86.0    Delhi
43           44   19   Male  1st Class      yes  95.0     Pune
45           46   20   Male  2nd Class      yes  79.0    Delhi
47           48   21   Male  2nd Class      yes  67.0     Pune
58           59   19   Male  1st Class      yes  89.0     Pune
63           64   20   Male  2nd Class      yes  78.0    Delhi
65           66   21   Male  3rd Class      yes  59.0     Pune
70           71   19   Male  1st Class      yes  85.0    Kochi
72           73   19   Male  1st Class      yes  89.0   Bhopal
74           75   20   Male  2nd Class      yes  79.0    Delhi
76           77   21   Male  2nd Class      yes  77.0     Pune
87           88   19   Male  1st Class      yes  96.0     Pune
92           93   20   Male  2nd Class      yes  74.0    Kochi
94           95   21   Male  3rd Class      yes  50.0   Bhopal
99          100   19   Male  1st Class      yes  84.0    Kochi
101         102   19   Male  1st Class      yes  98.0  Chennai
103         104   20   Male  2nd Class      yes  78.0   Mumbai
105         106   21   Male  2nd Class      yes  77.0    Kochi
116         117   19   Male  1st Class      yes  90.0    Kochi
121         122   20   Male  2nd Class      yes  75.0   Mumbai
123         124   21   Male  3rd Class      yes  49.0  Chennai
128         129   19   Male  1st Class      yes  89.0  Gwalior
130         131   19   Male  1st Class      yes  90.0  Chennai
132         133   20   Male  2nd Class      yes  75.0   Mumbai
134         135   21   Male  2nd Class      yes  75.0    Kochi
145         146   19   Male  1st Class      yes  98.0   Mumbai
150         151   20   Male  2nd Class      yes  78.0     Pune
152         153   21   Male  3rd Class      yes  46.0  Gwalior
157         158   19   Male  1st Class      yes  92.0     Pune
159         160   19   Male  1st Class      yes  92.0    Delhi
161         162   20   Male  2nd Class      yes  79.0     Pune
163         164   21   Male  2nd Class      yes  75.0  Gwalior
174         175   19   Male  1st Class      yes  84.0     Pune
179         180   20   Male  2nd Class      yes  76.0    Delhi
181         182   21   Male  3rd Class      yes  58.0     Pune
186         187   19   Male  1st Class      yes  83.0    Kochi
188         189   19   Male  1st Class      yes  89.0   Bhopal
190         191   20   Male  2nd Class      yes  77.0    Delhi
192         193   21   Male  2nd Class      yes  75.0     Pune
203         204   19   Male  1st Class      yes  91.0     Pune
208         209   20   Male  2nd Class      yes  70.0   Mumbai
210         211   21   Male  3rd Class      yes  58.0    Kochi
215         216   19   Male  1st Class      yes  95.0   Mumbai
217         218   19   Male  1st Class      yes  96.0    Kochi
219         220   20   Male  2nd Class      yes  75.0   Bhopal
221         222   21   Male  2nd Class      yes  74.0    Kochi
229         230   20   Male  3rd Class      yes  55.0    Delhi
231         232   20   Male  3rd Class      yes  59.0     Pune

In [107]:
#Create a new Column ‘IQ_level’ which will have 3 values (Intelligent, Mediocre, weak). If student scored than 80 then Tag him as Intelligent, if student scored between 50-80, then Mediocre, else weak.


conditions = [combined_df['Mark'] > 80,combined_df['Mark'].between(50, 80, inclusive='both')]

choices = ['Intelligent', 'Mediocre']

combined_df['IQ_level'] = np.select(conditions,choices,default='Weak')
combined_df['IQ_level']

0      Intelligent
1         Mediocre
2      Intelligent
3         Mediocre
4      Intelligent
          ...
227    Intelligent
228       Mediocre
229       Mediocre
230    Intelligent
231       Mediocre
Name: IQ_level, Length: 232, dtype: str

In [108]:
#Count the number of males and females from each city.
combined_df.groupby(['City','Gender'])['Student_id'].count()

City     Gender
Bhopal   Female    13
         Male      15
Chennai  Female    15
         Male      18
Delhi    Female    12
         Male      20
Gwalior  Female    14
         Male      18
Kochi    Female    10
         Male      21
Mumbai   Female    16
         Male      16
Pune     Female    15
         Male      26
Name: Student_id, dtype: int64

In [109]:
#Print the top 5 Male scorers.
male_top5 = ( combined_df[combined_df['Gender'] == 'Male'] .sort_values(by='Mark', ascending=False).head(5))
male_top5

     Student_id  Age Gender      Grade Employed   Mark     City     IQ_level
149         150   19   Male  1st Class       no  100.0   Bhopal  Intelligent
147         148   18   Male  1st Class       no   99.0    Kochi  Intelligent
62           63   19   Male  1st Class       no   98.0  Chennai  Intelligent
60           61   18   Male  1st Class       no   98.0  Gwalior  Intelligent
2             3   18   Male  1st Class       no   98.0   Mumbai  Intelligent

In [110]:
#Replace the Male value with M and Female value with F and export this dataframe to excel file in D: (D drive) and name the file as test.csv.

combined_df['Gender']=combined_df['Gender'].replace({'Male':'M','Female':'F'})
combined_df

     Student_id  Age Gender      Grade Employed  Mark     City     IQ_level
0             1   19      M  1st Class      yes  95.0  Chennai  Intelligent
1             2   20      F  2nd Class       no  70.0    Delhi     Mediocre
2             3   18      M  1st Class       no  98.0   Mumbai  Intelligent
3             4   21      F  2nd Class       no  75.0     Pune     Mediocre
4             5   19      M  1st Class       no  89.0    Kochi  Intelligent
..          ...  ...    ...        ...      ...   ...      ...          ...
227         228   21      F  1st Class       no  99.0     Pune  Intelligent
228         229   20      M  2nd Class       no  70.0  Chennai     Mediocre
229         230   20      M  3rd Class      yes  55.0    Delhi     Mediocre
230         231   19      F  1st Class      yes  97.0   Mumbai  Intelligent
231         232   20      M  3rd Class      yes  59.0     Pune     Mediocre

[232 rows x 8 columns]

In [88]:
#Export the file
combined_df.to_csv(r'D:\Career\Analytics Notes\Projects\Python\Pandas\test.csv', index=False)

In [111]:
#Check if any student_ID is duplicated.

combined_df.duplicated(subset=['Student_id']).sum()

np.int64(0)

In [112]:
# Create a separate dataframe which will have all the Integer/Float variables.
numeric_df = combined_df.select_dtypes(include=['int64', 'float64'])
numeric_df

     Student_id  Age  Mark
0             1   19  95.0
1             2   20  70.0
2             3   18  98.0
3             4   21  75.0
4             5   19  89.0
..          ...  ...   ...
227         228   21  99.0
228         229   20  70.0
229         230   20  55.0
230         231   19  97.0
231         232   20  59.0

[232 rows x 3 columns]

In [113]:
marks_df.rename(columns={'Student_id':'Student_id_M'}, inplace=True)

In [114]:
#Get those Student_IDs which are present in Students table but not in Marks table.
left_combined_df = pd.merge(student_df,marks_df, left_on='Student_id', right_on='Student_id_M',  how='left')

In [116]:
left_combined_df['Student_id_M'].isnull().sum()

np.int64(3)